### ISSUE TITLE
add PyUp (or another dependencies checker)

### ISSUE THREAD

**Issue by DmitryPoliuha** [vsvirsky/swagger2locustio#15]
PyUp.io lets you know when package dependencies are out of date or have security vulnerabilities. It automatically makes a pull request to update the package on GitHub.
On https://pyup.io/ register through GitHub, and connect your organization.

**Comment by vsvirsky** [comment]
No custom settings configured

We have not detected a .pyup.yml configuration file in the root directory of your repo. You can configure the PyUp bot by creating this file.

Please take a look at the PyUp docs on how to configure the bot.

Based on our defaults, your current settings are:
Update: all
Search: True
Pin: True
Default Branch: master
Branch pre-fix: pyup-
Close PRs: True
Label PRs: False
Update hashes: True


https://pyup.io/docs/bot/config/
