### ISSUE TITLE
refactor project to pass pylint checks

### ISSUE THREAD

**Issue by DmitryPoliuha** [vsvirsky/swagger2locustio#29]

**Comment by olehkrupko** [comment]
string errors: "use % formatting in logging functions and pass the % parameters as arguments (logging-format-interpolation)" (f-strings were used)

It is possible to change pylint behaviour ( https://stackoverflow.com/a/59027338 ) or refactor f-strings to % formatting

Decided by @vsvirsky to go for second option and switch to % formatting
